name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Setup PureScript dependencies
        run: npm i --global purescript@0.15.15 esbuild spago@next purs-tidy

      - name: Check formatting
        run: purs-tidy check src/

      - name: Build source
        run: |
          spago build --strict

      - name: Run tests
        run: spago test

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.yaml') }}
          path: |
            .spago
            output

